name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # Run tests
      - name: Run Tests
        run: mvn -B test