name: CI Pipeline (DOC1)

on:
  # Manually trigger workflow runs
  workflow_dispatch:
  # Trigger the workflow on push from the main branch
  push:
    branches: [ master ]

jobs:
  # Build job
  build:
    name: My First Pipeline
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo "CI in GitHub actions"
        